CREATE OR REPLACE FUNCTION CURSOS(IN BOM_ID INT)
RETURNS 
/*Este procedimiento devolvera una tabla*/
TABLE(
	NOMBRE VARCHAR,
	DESCRIPCION VARCHAR,
	FECHA DATE
)
AS $$
BEGIN
/*Aqui efectuamos la consulta*/
	RETURN QUERY
	SELECT 
	BOMBERO.NOMBRE_BOMBERO,
	CURSO.DESCRIPCION_CURSO,
	CURSO.FECHA_INICIO_CURSO
	FROM BOMBERO
	INNER JOIN BOMBERO_CURSO ON BOMBERO_CURSO.ID_BOMBERO=BOMBERO.ID_BOMBERO
	INNER JOIN CURSO ON BOMBERO_CURSO.ID_CURSO=CURSO.ID_CURSO
	WHERE BOMBERO.ID_BOMBERO=BOM_ID;
END
$$
LANGUAGE 'plpgsql'


SELECT * FROM CURSOS(2);

